spring.application.name=springmvc


spring.datasource.url=jdbc:sqlite:src/main/resources/springmvc.sqlite3
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=1BohNK7sdn1leSeP4b2qMvSdfLSZUH76
jwt.expiration=3600000
server.port=8080
x-api-key=p2FIUj18vkorCPa43FcbKV6tu6BW1bsi

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.url=/api-docs
springdoc.swagger-ui.path=/swagger-api-docs